version: '3.8'

services:
  db:
    image: mysql:8
    container_name: wp_db
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - wpnetwork

  wordpress:
    image: wordpress:latest
    container_name: wp_cms
    depends_on:
      - db
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      - WORDPRESS_DB_HOST=${DB_HOST}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - wpnetwork

networks:
  wpnetwork:
